.\"
.\" Copyright 2007 Werner Fink, 2007 SuSE GmbH Nuernberg, Germany.
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.TH FSYNC 1 "Jun 18, 2007" "Version 1.16" "The SuSE boot concept"
.UC 1
.SH NAME
fsync \- synchronize the specified file with storage device
.\"
.SH SYNOPSIS
.\"
.B fsync
.I file
.\"
.SH DESCRIPTION
.B fsync
synchronize the in-core state of the specified file with the storage device
.\"
.SH BUGS
The
.B fsync
program uses the
.BR fsync (2)
function and therefore shows the same weaknesses
by any system activity.
.\"
.SH SEE ALSO
.BR fsync (2),
.BR fdatasync (2).
.\"
.SH COPYRIGHT
2007 Werner Fink,
2007 SuSE GmbH Nuernberg, Germany.
.SH AUTHOR
Werner Fink <werner@suse.de>
